on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2.3.4

      - name: Install Crystal
        uses: oprypin/install-crystal@693fe2f9434fc3948600392b96db3fb4a06dda8e

      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run lint
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
