on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2.4.0

      - name: Install Crystal
        uses: oprypin/install-crystal@822c1ae16239de8f175f7e89af6eef008b29a8ec

      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run lint
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
