on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3.3.0

      - name: Install Crystal
        uses: oprypin/install-crystal@bf1b0576fd275460f9d3b034005d2d9a506fa274

      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run lint
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
