on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2.3.4

      - name: Install Crystal
        uses: oprypin/install-crystal@908d8693d6b3299df5b821334de7dd95c7079695

      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run lint
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
