on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2.4.0

      - name: Install Crystal
        uses: oprypin/install-crystal@87a1c8a577ccef16c569f1fe46db81a435e66c05

      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run lint
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
